{
 "title": "Rolls Values Frequency Enhanced",
 "description": "The Frequency of each possible number",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "Latency (P95)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests ≤ 250 ms (%)\t",
   "type": "stat",
   "description": "Percentage of requests whose latency fell at or below 250 ms in the last minute (p = rate over 1 m)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{le=\"0.25\"}[1m])) / sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (P99)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#. Slow requests > 250 ms (last min)",
   "type": "stat",
   "description": "Number of slow requests whose latency fell above 250 ms in the last minute (p = rate over 1 m)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(increase(http_requests_total[1m])) -\n  sum(increase(http_request_duration_seconds_bucket{le=\"0.25\"}[1m]))\n)"
    }
   ]
  },
  {
   "title": "Latency (P50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Primary Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Rolls Values Frequency",
   "type": "piechart",
   "description": "The frequency of each possible number.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dice_rolls{job=\"dice-server\"}",
     "legendFormat": "Value: {{roll_value}}"
    }
   ]
  },
  {
   "title": "Latency (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic (Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (status_code,route)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traces (Drill Down)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "All Traces",
   "type": "table",
   "description": "Query Used is: {}",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{}",
     "spss": 8,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces with Errors",
   "type": "table",
   "description": "Query used: {status=error}",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "{status=error}", "tableType": "traces" }
   ]
  },
  {
   "title": "Traces Panel",
   "type": "traces",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "filters": [
      { "id": "05f27f9c", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "dice-server" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "error",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "${traceId}",
     "tableType": "traces"
    }
   ]
  }
 ]
}